Homework
P5CHI-Web-Academy/HomeWork_TestingVueApplications pull request #2
Opened 2019-06-03 11:59 UTC by eclimov

**Added tests:**
_SpicesOrderPreviewList.spec.js_
- correct amount of list items rendered
- spice can be removed from list of preordered spices
- check that click `Add to Order` triggers corresponding event
_Order.spec.js_
- check store for items in order
- action `updateQuantity` is triggered when clicking corresponding buttons
- `clearOrder` is called when [clear] button is clicked
- `discount` message is rendered, when there is discount
- `discount` message is NOT rendered, when there is no discount

**Added features:**
- added possibility to remove item from preorder
- implemented "Order" page:
possibility to clear "order items" list;
possibility to increase/decrease quantity of any item in order list. If quantity <=0, item is removed from the order automatically;
- implemented "discount" logic: order gets a 20% discount if more than 3 types of items are in order or at least one item has quantity more than 3 in order
- added "price" attribute to item
- added useful info on pages:
price near each item;
discount conditions on the right side of the page;
"DISCOUNT" text near "Order" tab and below "Order details" section;

**Improvements:**
- renamed key "orderId" to "spiceId" in remoteData
- added missing "required" attribute to props of some components
- removed unused code
- reordered attributes of some components according to eslint suggestions

2019-06-03 21:25 UTC, lkoida requested changes
Not bad. Thanks for work

2019-06-03 21:25 UTC, lkoida commented on tests/unit/specs/views/Order.spec.js
> +import Order from '../../../../src/views/Order'
you can use alias `@` and get rid of all this part `../../../../src`. Take a look at jest.config.js there is a property `moduleNameMapper`
so as a result, this import should look as `@/views/Order`

2019-06-03 21:25 UTC, lkoida commented on tests/unit/specs/views/Order.spec.js
> +
It looks like you forgot to add `flushPromises` library. This library checks if all promises are resolved/rejected. You should include it before expectations

2019-06-03 21:25 UTC, lkoida commented on tests/unit/specs/views/Order.spec.js
> +
the same here, `flushPromises` missing, and in this case your async statement is useless because all code executing before the promises set state to resolved/rejected

2019-06-03 21:25 UTC, lkoida commented on src/views/Order.vue
> +            <b>{{ item.price }} &euro;</b>
You use same string formatting in some different places( add EURO sign) this is perfect case to implement filter and use it. The benefit - you have all transformation logic centralized and final usage can look like this: `{{ item.price | currency }}`

2019-06-04 07:00 UTC, eclimov commented
Done

2019-06-04 21:08 UTC, lkoida requested changes
check additional comments

2019-06-04 21:08 UTC, lkoida commented on src/main.js
> +  return value + ' \u20AC' // euro sign
:+1: 
some small improvements:
1 - add check if value is missing
2 - use string template literals: `${value} \u20AC`
3 - replace all places with euro - you missed some
4 - as a suggestion  - move your filters to dedicated directory, to not pollute main.js file

2019-06-05 08:24 UTC, eclimov commented
Done

2019-06-06 13:21 UTC, merged